[package]
name = "fproxy"
version = "0.0.1"
edition = "2024"
keywords = ["ffi", "rust-to-rust-ffi", "dynamic", "linking"]
categories = ["development-tools::ffi", "game-development", "game-engines", "rust-patterns"]
license = "MIT"
description = "Facilitate safe rust-to-rust ffi by generating proxies around required types. Useful when a library is loaded at runtime (i.e., dynamic)."
homepage = "https://github.com/Plegeus/fproxy"
repository = "https://github.com/Plegeus/fproxy"
readme = "README.md"

[dependencies]
fproxy_derive = { path = "./../fproxy_derive", version = "0.0.1" }
libloading = "0.8.9"
safer-ffi = "0.1.13"
delegate = "0.13.4"


